---
title: "Research"
#description: |
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

As a young child, I did not have many other family or friends around. Many of my childhood experiences were fairly solipistic. My mother was a single parent in the military and as such, we traveled often. We often lived places where we did not know anyone else, and no one knew us. What I found in philosophy, was a kind of community. Some of my most memorable moments in academia are being in a room with other philosphers, asking questions and listening to attempted answers. In the activity, I found solidarity and community.

My research revolves around the fundamental question of whether there exists a relationship between moral knowledge and popular narratives, particularly those embedded within cultural artifacts more broadly. Music, in my opinion is a form of community dialogue, socialization. Socialization primarily involves education, at least education is a form of socialization. Through it, individuals are added to the society. In my teaching, I hope to draw connections between a student's broader sociological experiences, the various forms of dialogue that exist in a democratic society, and the material that we cover in my courses. Namely, a central experience for us, includes our deep and meaningful relationships with others that are grounded in healthy communication. I like to tie my interests in moral epistemology holistic education. For me, this includes the ability to foster healthy relationships through meaningful dialogue.

To encourage such an approach to philosophy, I begin with a little thought experiment. I ask the students to imagine an intimate dinner party among family and close friends. On the one hand, we might be inclinded to shy away from more sensitive subject matter such as politics and religion. However, these subject matters are often ones that can define us. Their answers can hold value for our lives. Our answers to these questions then, are weighty. On the one hand, those we can have such conversations with, are likely those individuals who love us unconditionally. As such, these are those individuals who care about us regardless of what we believe. But on the other, I like to think that philosophy gives us the ability to talk about such sensitive subject matter in a way that does not undermine any relationships that bring even a modicum of value to our lives. Importantly, I hope to show my students that while our beliefs may be important for us, what is more important is the activity of thinking about and sharing our beliefs.

Therefore, one of the most important things that my time at Saint Louis University has taught me, is that education is centered on compassion *and* understanding, as it relates to the human experience. Our compassion motivates us to understand the views of others. These are virtues that are important in having meaningful, memorable conversations that build connections rather than undermine them.

In my teaching, I draw inspiration from notable thinkers like Robert Hopkins, Nomy Arpaly, David Enoc, Laura Callahan, Jesse Prinz, and Michael Slote, who have championed ethical theories such as emotionism and sentimentalism. According to these philosophical views, there is a deep connection between our emotions and our moral judgments. I think that such connections are important because they help us to understand what we value. I organize my teaching materials around the principle that in order for a concept to be memorable, it must in some way have intrinsic value for the student. These can be memorable moments in the course, such as a question that they were motivated to pursue on their own. As such, I try to highlight parts of an assignment that may mean the most to a student's internal life. I try to connect the assignment with them in a way that requires them to ask their own questions of the material, if for no other benefit than the activity itself. Several of my favorite assignments encourage the students to recognize when a reading is embedding implicit premises by attempting to motivate certain emotions from the reader. For these, I might mention popular movies that implicitly make philosophical arguments. For instance, Cider House Rules, starring a young Toby McGuire as it is an implicit defense of medical decisions.

Following individuals such as Eleonore Stump (2020) and Martha Nussbaum, I anchor my research in the context of human well-being drawing upon psychological studies which emphasize the role of narratives in community-building by enhancing emotional bonds among its members. In the rich landscape of psychological literature on narratives, individuals such as Jerome Bruner (1991), E.H. Erikson (1968), narratives are seen as pivotal tools that inform our self-identity, and infuse our lives with meaning, an important component of psychological development. I often assign readings that suggest how philosophy can motivate questions about self-identity and how such questions are central to a well-lived life. Approaching the material this way, I believe will have a greater impact on the student's ability to retain, not merely the information we discuss, but the activity of active reading itself. This kind of activity encourages the student to actively read the material. Active reading requires that the student questions the material, seek ways to clarify the material, summarize, and finally offer predictions as to how that author might answer a question not found directly in the material.

When students begin to have families and careers, there may be a temptation to stop thinking about philosophical questions, for instance those about what makes a life good. However, a central focus of a democratic society are questions about what is best for the public. These are questions which the public is tasked with asking and determining by our participation in the electoral process. As such, in a democratic society wherein a large portion of governence relies on the public's ability to think about such questions, there is reason to think that our thinking about, and asking questions related to the good-life, are obligations for citizens in a democratic society. Therefore these are questions we not only should be asking ourselves, but also each other. My aim is to strongly encourage my students to think about such questions through what Susan @ambr10 calls active learning. As such, philosophical thinking is a kind of activity that my courses provide a safe space to for students to pursue. The most important concept that I grade my students on, is whether they have thought about the material.

In terms of my professional journey, I have gained valuable experience in the academic realm. From 2019 to 2021, I served as an assistant to the editor for the academic journal Res Philosophica. In this role, I meticulously edited journal submissions, ensuring compliance with style standards, built bibliography libraries, and convert documents from various formats into LaTex.

Continuing my academic pursuits, I became a member of Feminist X-Phi, an innovative research collaboration hosted at CUNY Graduate Center, from 2021 to 2022. Within this dynamic environment, I not only presented my own research regularly but also collaborated with fellow members on empirical projects, showcasing my ability to work effectively within research-focused communities.

In 2022, I furthered my research expertise as a research assistant at the Walter J. Ong Center for the Digital Humanities. During this year-long assistantship, I delivered presentations on tools for annotating objects in machine learning and conducted comparative analyses of sentiment analysis algorithms using Python and R.

Outside the realm of academia, I am dedicated to maintaining a tutorial website on sentiment analysis in data science, which aids in understanding emotional expressions in popular media, with a particular focus on popular songs. Beyond my professional commitments, I cherish spending quality time with my family, engaging in activities such as playing video games with my son, creating plays and shows with my daughter, and witnessing the developmental milestones of our newest addition. Additionally, I relish going on walks with my wife, as it provides a welcomed balance to my academic pursuits.

# Dissertation Abstract

In critical race theory, there is a rarely cited concern regarding the importance of social identity for racial equality. However, much of the literature does little to identify many of the contemporary ways in which social identity is constructed. In my proposal, I engage in a conceptual analysis of several genres of music and their representations of various moral norms and social values. I especially contrast country music against hip-hop. A central point of this proposal is that much of the content of hip-hop is grounded in market forces rather than community standards and values. This means that the communities represented by the music have little say in the representations of moral norms or social values attributed to them. I further argue that this misconstruction of a community's values has implications for the well-being of that community. In defense of this argument, I look at moral epistemology, especially moral testimony and moral feeling. I argue that moral testimony is an important component of moral feeling for knowledge and identity. I then argue that narratives in music constitute a kind of moral knowledge because of its role in constructing social identities by creating pathways between feeling and moral objects in musical narratives. I argue that in this way, music plays a central role in constructing social identities and therefore is important for the well-being of that community.

My dissertation addresses two central questions for moral epistemologists and cognitivists. According to (1), moral testimony is untenable. Epistemologists Alison Hills (2009, 2013) and Sarah McGrath (2018), have published a worry that accepting or acting on moral testimony, while potentially valuable, cannot be justified. Moral actions that are based on moral testimony would have no moral worth. A number of explanations have been given as to why this is the case. However, some of the more plausible explanations share an important feature with the second central question. We often expect active agency in the context of moral behavior. It is not enough that we act rightly, but our action ought reflect our understanding regarding the correct action. Moral reflection unlike non-moral reflection however, requires a richer form of understanding involving both cognitive and non-cognitive faculties. The right emotion ought accompany our moral action. Like (1), (2) also concerns emotions. We have emotions toward fictions, however, these do not always mirror those we have in the real world. In some situations, our emotional responses to fictions are apt though they are inapt outside of such contexts, e.g., slap-stick comedy. The right emotion need not accompany the audience of art. Jonathan Gilmore (2021) argues that our emotions towards a given fiction is often justified just in case the emotion was the one intended by the author. The second problem concerns the aptness of an expressed emotion.

In chapter 2, I examine the relationship between fiction and the more robust form of moral understanding important for attributions of moral worth. I contrast standard epistemological cases with moral epistemological ones. Chapter 3 explores philosophical accounts of narrative. Following notable optimists in the literature on moral testimony, such as Eleonore Stump and Martha Nussbaum, I argue that narrative is a potential avenue for achieving affective moral understanding. I define affective moral understanding as feeling the right way at the right time in response to the right object. The philosophy of psychology addresses those concerns in moral epistemology regarding the importance of moral narratives. In chapter 4, I look at psychological accounts of narrative. I focus on a class of such accounts that draw a connection between narrative understanding and human flourishing. Finally, in chapter 5, I consider whether literary narratives central to human flourishing are necessarily classical works of literature. The question about apt emotional expression and art is often articulated as a form of moral enhancement. Art is said to have the ability to make us better persons. For instance, Elizabeth Glaskill’s “Mary Barton” is often credited with motivating the expanded public health care and other social goods that the United Kingdom provides. However, rarely is popular music discussed. Yet, it is likely that a greater proportion of a given population consume popular music rather then classical literature. I argue this raises a problem: if only classical works are central to human flourishing, then only classical works can potentially undermine human flourishing. So I expand my investigation to consider a class of non-classical works, namely popular narratives. Analyzing these narratives, I develop a model of non-classical literary works that satisfy both philosophical and psychological accounts of the close connection between narrative and human flourishing.
