---
title: "Research"
#description: | 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

My research revolves around the fundamental question of whether there exists a relationship between moral knowledge and popular narratives, particularly those embedded within music. Drawing inspiration from notable thinkers like Robert Hopkins, Nomy Arpaly, David Enoc, Laura Callahan, Jesse Prinz, and Michael Slote, who have championed ethical theories such as emotionism and sentimentalism, I delve into the multifaceted claims surrounding the idea that these theories connect our emotions with our moral judgments.

Following individuals such as Eleonore Stump (2020) and Martha Nussbaum, I anchor my research in the context of human well-being drawing upon psychological studies which emphasize the role of narratives in community-building by enhancing emotional bonds among its members. In the rich landscape of psychological literature on narratives, individuals such as Jerome Bruner (1991), E.H. Erikson (1968), narratives are seen as pivotal tools that inform our self-identity, and infuse our lives with meaning, an important component of psychological development.

In terms of my professional journey, I have gained valuable experience in the academic realm. From 2019 to 2021, I served as an assistant to the editor for the academic journal Res Philosophica. In this role, I meticulously edited journal submissions, ensuring compliance with style standards, built bibliography libraries, and convert documents from various formats into LaTex.

Continuing my academic pursuits, I became a member of Feminist X-Phi, an innovative research collaboration hosted at CUNY Graduate Center, from 2021 to 2022. Within this dynamic environment, I not only presented my own research regularly but also collaborated with fellow members on empirical projects, showcasing my ability to work effectively within research-focused communities.

In 2022, I furthered my research expertise as a research assistant at the Walter J. Ong Center for the Digital Humanities. During this year-long assistantship, I delivered presentations on tools for annotating objects in machine learning and conducted comparative analyses of sentiment analysis algorithms using Python and R.

Outside the realm of academia, I am dedicated to maintaining a tutorial website on sentiment analysis in data science, which aids in understanding emotional expressions in popular media, with a particular focus on popular songs. Beyond my professional commitments, I cherish spending quality time with my family, engaging in activities such as playing video games with my son, creating plays and shows with my daughter, and witnessing the developmental milestones of our newest addition. Additionally, I relish going on walks with my wife, as it provides a welcomed balance to my academic pursuits.

# Dissertation Abstract

My dissertation addresses two central questions for moral epistemologists and cognitivists. According to (1), moral testimony is untenable. Epistemologists Alison Hills (2009, 2013) and Sarah McGrath (2018), have published a worry that accepting or acting on moral testimony, while potentially valuable, cannot be justified. Moral actions that are based on moral testimony would have no moral worth. A number of explanations have been given as to why this is the case. However, some of the more plausible explanations share an important feature with the second central question. We often expect active agency in the context of moral behavior. It is not enough that we act rightly, but our action ought reflect our understanding regarding the correct action. Moral reflection unlike non-moral reflection however, requires a richer form of understanding involving both cognitive and non-cognitive faculties. The right emotion ought accompany our moral action. Like (1), (2) also concerns emotions. We have emotions toward fictions, however, these do not always mirror those we have in the real world. In some situations, our emotional responses to fictions are apt though they are inapt outside of such contexts, e.g., slap-stick comedy. The right emotion need not accompany the audience of art. Jonathan Gilmore (2021) argues that our emotions towards a given fiction is often justified just in case the emotion was the one intended by the author. The second problem concerns the aptness of an expressed emotion.

In chapter 2, I examine the relationship between fiction and the more robust form of moral understanding important for attributions of moral worth. I contrast standard epistemological cases with moral epistemological ones. Chapter 3 explores philosophical accounts of narrative. Following notable optimists in the literature on moral testimony, such as Eleonore Stump and Martha Nussbaum, I argue that narrative is a potential avenue for achieving affective moral understanding. I define affective moral understanding as feeling the right way at the right time in response to the right object. The philosophy of psychology addresses those concerns in moral epistemology regarding the importance of moral narratives. In chapter 4, I look at psychological accounts of narrative. I focus on a class of such accounts that draw a connection between narrative understanding and human flourishing. Finally, in chapter 5, I consider whether literary narratives central to human flourishing are necessarily classical works of literature. The question about apt emotional expression and art is often articulated as a form of moral enhancement. Art is said to have the ability to make us better persons. For instance, Elizabeth Glaskill’s “Mary Barton” is often credited with motivating the expanded public health care and other social goods that the United Kingdom provides. However, rarely is popular music discussed. Yet, it is likely that a greater proportion of a given population consume popular music rather then classical literature. I argue this raises a problem: if only classical works are central to human flourishing, then only classical works can potentially undermine human flourishing. So I expand my investigation to consider a class of non-classical works, namely popular narratives. Analyzing these narratives, I develop a model of non-classical literary works that satisfy both philosophical and psychological accounts of the close connection between narrative and human flourishing.
