---
title: "Curriculum Vitae"
#description:
author:
  - name: Monty
    url: {}
date: 2023-09-12
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Adorjan Hall 130 * 3800 Lindell Blvd * Saint Louis, MO 63108  
montaque.reynolds@slu.edu * www.montaque-reynolds.com   
206-234-3477 (c) * 314-977-3149 (w)

### Dissertation Title

Emotional Datum and Meaning: An analysis of the moral expression of sentiment in fiction

### Area of Specialization

Philosophy of Mind, Meta-Ethics

### Area of Competence

Philosophy of Law, Ethics, Epistemology

### Education 

Ph.D. Philosophy, Saint Louis University 2024 (Expected)

M.A. Philosophy, Oklahoma State University 2017

B.A. Philosophy, Seattle Pacific University 2015

## Publications

Chakrabarty, Urna, Romy Feiertag, Anne-Marie McCallion, Brian McNiff, Jesse Prinz, Montaque Reynolds, Sukhvinder Shahi, Maya Von Ziegesar, and Angella Yamamoto. “Adaptive Preferences: An Empirical Investigation of Feminist Perspectives.” In Experiments in Moral and Political Philosophy, 310–30. Routledge Studies in Ethics and Moral Theory. Routledge, 2024.

## Conferences

### Presentations (Selected)

2023 *Love and Wonder in Country Music: Objective not relative authenticity and value in country music*, American Society of Aesthetics, Santa Fe, New Mexico

2022 *Aesthetic Blame, Robbie Kubala*, Pacific Division American Society of Aesthetics, Berkeley, California

2022 *Getting Things Right in Country Music: An Account of Meaning in Country*, Panel on Country Music at the General Meeting of the American Society for Aesthetics

2022 *Sensible Self-Censorship: TV Guide to Love and Friendship*, Rocky Mountain Division of the American Society of Aesthetics, Santa Fe, California

2020 *Conative Moral Testimony*, 26th Annual Graduate Research Symposium (Online Poster), Saint Louis University

2019 *Basically, You Are Justified: A knowledge first account of religious belief*, 12th Annual LSU Graduate Philosophy Conference, Louisianna State University, Baton Rouge, LA

2018 *Plantinga’s Unique Naturalism as a Criticism of Evolutionary Reliabilism*, Great Lakes Philosophy Conference, Sienna Heights University, Adrain, MI

2017 *Convenience and Correspondence: Plantinga’s Unique Naturalism as a Criticism of Evolutionary Reliabilism in Nature and Beyond*, Transcendence and Immanence in Science and Religion (ECST XVII), 69130 écully France

2017 *The Evolution of Religious Belief*, The Evolution of Religion II, Bernalilo, New Mexico

### Organizer

2022 Panel on Country Music with John Dyck and Evan Malone, General Meeting of the American Society of Aesthetics, Portland, OR

2022 Saint Louis University PGSA Conference, The Problem of Evil, Co-Organizer

2021 Saint Louis University PGSA Conference, Virtue and Wisdom, Co-Organizer

## Teaching Experience 

### Instructor of Record

2023 *The Examined Life: Phil 1700-02*, Saint Louis University (Asynchronous, Philosophy-Digital Humanities Collaboration)

2022 *Introduction to Ethics: Phil 2050*, Saint Louis University (Asynchronous)

2021 *Introduction to Ethics: Phil 2050*, Saint Louis University

2016 *Philosophies of Life: Phil 1213* Oklahoma State University 

### Graduate Teaching Assistant

2019 Graduate Teaching Assistant, *Introduction to Philosophy: Phil 1050*, Saint Louis University

2018 Graduate Teaching Assistant, *Introduction to Philosophy: Phil 1050*, Saint Louis University

2017 Graduate Teaching Assistant, *Philosophy of Law: Phil 3843*, Oklahoma State University

2016 Graduate Teaching Assistant, *Philosophies of Life: Phil 1213*, Oklahoma State University

2015 Graduate Teaching Assistant, *Philosophies of Life: Phil 1213*, Oklahoma State University

### Research Experience 

2022 Research Assistant, *Walter J. Ong Center for the Digital Humanities*

2021---2022 CUNY Graduate School Feminist Experimental Philosophy Research Group (Virtual)

2019 --- 2021 Assistant to the Editor, *Res Philosophica*

## Professional Memberships

2020 --- Present, *American Society for Aesthetics*

2018 --- Present, *American Philosophical Association*

## Honors, Fellowships, and Awards

2022 Digital Humanities Fellowship

2022 Collins Award

2022 Irene H. Chayes Graduate Award for Sensible Self-Censorship: The TV Guide to Love and Friendship, Rocky Mountain Division of the American Society for Aesthetics, Santa Fe, NM

2022 Best Graduate Essay Prize for Sensible Self-Censorship: The TV Guide to Love and Friendship, Rocky Mountain Division of the American Society for Aesthetics, Santa Fe, NM

2022 Saint Louis University Edward L. and Rhelda Marbry Morgan, Ph.D. Book Fund

### List of Courses Taken

**Science, Logic**

PHIL 6220 --- Advanced Logic (Joseph Salerno)

**Metaphysics, Epistemology**

PHIL 4WU (Washington University) --- Topics in Ethics: Desire (Alan Hazlett, Washington University)

PHIL 6340 --- Issues in Epistemology (John Greco)

PHIL 6930 --- Belief and the Doxastic Family (Joseph Salerno and Pascal Pierre Denis Engel)

PHIL 6500 --- Modern Philosophy: Hume & Reid (Joseph Salerno)

PHIL 6300 --- Agents and Agency (Kathryn Lindeman)

PHIL 6260 --- Suffering: Christian & Jewish (Eleonore Stump)

**Value Theory**

PHIL 6000 --- Seminar in Major Philosopher in Ethics: Aristotle (Gregory Beabout)

PHIL 6300 --- Advanced Ethics: Genealogies of Morality (Helen De Cruz)

PHIL 6360 --- Seminar in Political Philosophy: Political Morality (Daniel Haybron)

**Digital Humanities**

ASTD 5930 --- Special Topics: Digital Humanities (Adam Park)

### Notable Workshops

2022 *Deep Learning for Humanists*

2021---2022 *Towards a feminist x-phi workshop series*

2021 CoLiPhi *Corpus Linguistics and Philosophy*, three day workshop on Corpus linguistics and experimental philosophy

### Languages and Skills

R, LaTex, Python
