---
title: Teaching
---

Due to frequent moves as a child, I seldom had the opportunity to form lasting connections. Then, literature provided me with something like a semblance of a lasting connnection. Since then, philosophy has provided me with a sense of community and solidarity, which has inspired my passion for education.

In my course work, I aim to cultivate a culture of scholarship. Drawing on Susan Ambrose's (2010) principle that prior knowledge shapes learning, I aim to connect students' sociological experiences with their existing knowledge in my teaching.

In the following interactive and downloadable document, I articulate my teaching philosophy, experiences, and future aspirations.

<iframe src="https://drive.google.com/file/d/1lDecZ02fzlXOGm9aaTm3ksRETKfEfuZP/preview" width="100%" height="400px" allow="autoplay"></iframe>

### Evaluations

Here, you will find some teaching evaluations.

<iframe src="https://drive.google.com/file/d/1mxm8UtCGzJS65FvbBT6yDPV-Nm48iCCn/preview" width="640" height="480" allow="autoplay"></iframe>

<iframe src="https://drive.google.com/file/d/117wesKJeyP3903hMyjUARxxx7bs9CFG5/preview" width="640" height="480" allow="autoplay"></iframe>
